/********************************************************************
 * Script: formatAmountForOutput.js
 *
 * WHAT IT DOES
 * - Takes an input called "amount" from an Airtable automation script.
 * - Safely normalizes different input formats:
 *      • Number (e.g. 12.3)
 *      • String (e.g. "12.30")
 *      • Single item arrays from lookups (e.g. ["12.30"])
 *      • Empty values and empty arrays
 * - Returns a formatted string with 2 decimal places using en-CA rules.
 * - Returns an empty string when there is no usable numeric value.
 *
 * WHEN IT IS USEFUL
 * - When you need clean, human-friendly currency or numeric formatting
 *   for emails, PDFs, or messages generated by Airtable automations.
 * - When your source value comes from lookup or rollup fields that
 *   sometimes produce arrays with a single item.
 * - When you want consistent formatting from mixed sources, such as
 *   numbers in some records and strings or arrays in others.
 *
 * HOW TO USE IT IN AN AIRTABLE AUTOMATION
 * 1. Add an action "Run a script".
 * 2. Create an input variable for the script:
 *      • Name: amount
 *      • Value: map it to the field that contains your amount
 *        (this can be a number field, formula, lookup, etc.).
 * 3. Paste this script into the script step.
 * 4. The script will output:
 *      • formattedValue   → a string like "123.45" or "" (empty string).
 * 5. In later automation steps (email, update record, etc.) use:
 *      {{formattedValue}} as the formatted value.
 *
 * NOTES
 * - This script does not add a currency symbol, only a numeric string.
 * - Locale is set to "en-CA" so decimals and thousands separators
 *   follow that numbering style.
 ********************************************************************/


/********************************************************************
 * CONFIGURATION
 ********************************************************************/
const CONFIG = {
    inputKeys: {
        amount: "amount"   // Name of the script input variable for Amount
    }
};

/********************************************************************
 * INPUT LOADING
 ********************************************************************/
const inputConfig = input.config();
const rawAmount = inputConfig[CONFIG.inputKeys.amount];

/********************************************************************
 * HELPER: Normalize amount input
 * Handles:
 *  - Numbers
 *  - Strings
 *  - Single item arrays from lookups, like ["123.45"]
 *  - Empty values (null, undefined, [], [""])
 ********************************************************************/
function normalizeAmount(value) {
    // Handle arrays like ["123.45"] or [123.45]
    if (Array.isArray(value)) {
        if (value.length === 0) return null; // Empty lookup
        // Take the first non-null item, if any
        const firstNonNull = value.find(v => v !== null && v !== undefined);
        if (firstNonNull === undefined) return null;
        return normalizeAmount(firstNonNull); // Reuse same logic
    }

    // Null or undefined means "no value"
    if (value === null || value === undefined) {
        return null;
    }

    // Strings: trim and parse
    if (typeof value === "string") {
        const trimmed = value.trim();
        if (trimmed === "") return null;
        const parsed = Number(trimmed);
        return Number.isNaN(parsed) ? null : parsed;
    }

    // Numbers: use as is
    if (typeof value === "number") {
        return value;
    }

    // Any other type is not supported, treat as no value
    return null;
}

/********************************************************************
 * HELPER: Currency Formatter
 ********************************************************************/
const currencyFormatter = new Intl.NumberFormat("en-CA", { 
    style: "decimal", 
    minimumFractionDigits: 2, 
    maximumFractionDigits: 2 
});

/********************************************************************
 * MAIN LOGIC
 ********************************************************************/
const amount = normalizeAmount(rawAmount);

let formattedValue;

// If no usable number, return empty string so it is easy to handle in later steps
if (amount === null) {
    formattedValue = "";
} else {
    formattedValue = currencyFormatter.format(amount);
}

/********************************************************************
 * OUTPUT
 ********************************************************************/
output.set("formattedValue", formattedValue);
